### ISSUE TITLE
`componentDidUnmount`? Shouldn't it be `componentWillUnmount`?

### ISSUE THREAD

**Issue by afilp** [reactnativecn/react-safe-promise#1]
Does this work? Because I get warnings because there is no such lifecycle method like `componentDidUnmount`. Shouldn't it be `componentWillUnmount`?

```
    componentDidUnmount(){
      super.componentDidUnmount();
```

**Comment by tdzl2003** [comment]
Yes, it should be `componentWillUnmount`,thanks.

**Comment by afilp** [comment]
The problem is that it does not work with componentWillUnmount, it cannot call the callbacks on undefined. I did exactly as proposed and changed to `componentWillUnmount`, but it does not work. Any ideas? Thank you.

**Comment by afilp** [comment]
The error I get is the following:

`Cannot read property 'call' of undefined`

**Comment by tdzl2003** [comment]
Could you please post your code & error stack?
